name: nexa_http_native_ios
description: iOS native carrier package for nexa_http artifacts and build integration.
version: 1.0.1
publish_to: none
environment:
  sdk: ^3.11.0
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  code_assets: ^1.0.0
  hooks: ^1.0.2
  nexa_http_native_runtime_internal:
    path: ../nexa_http_native_runtime_internal
  path: ^1.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.3

flutter:
  plugin:
    implements: nexa_http
    platforms:
      ios:
        dartPluginClass: NexaHttpNativeIosPlugin
        ffiPlugin: true
